<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        User
 */
namespace entity; // toujours le même nom que le dossier, pour que l'autoload puisse trouver le fichier
require_once('User.class.php');

class Admin extends User {

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $nom;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $prenom;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $email;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $sexe;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $ville;

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $cp;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $adresse;


}
?>