<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */
namespace entity; // toujours le même nom que le dossier, pour que l'autoload puisse trouver le fichier
class Avis {

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $id_avis;

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $id_membre;

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $id_salle;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $commentaire;

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $note;
        
        /**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $note;
        
         //----------- GETTERS -----------------
    public function getIdAvis()
    {
        return $this->idAvis;
    }
    public function getIdMembre()
    {
        return $this->idMembre;
    }
    public function getIdSalle()
    {
        return $this->idSalle;
    }
    public function getCommentaire()
    {
        return $this->commentaire;
    }
    public function getNote()
    {
        return $this->note;
    }
    public function getDate()
    {
        return $this->date;
    }
   
    //--------- SETTERS ------------------
    public function setIdAvis($arg)
    {
        // traitements ...
        $this->idAvis = filter_has_var(INPUT_POST, $arg);
    }
    public function setIdMembre()
    {
        return $this->idMembre;
    }
    public function setIdSalle()
    {
        return $this->idSalle;
    }
    public function setCommentaire()
    {
        return $this->commentaire;
    }
    public function setNote()
    {
        return $this->note;
    }
    public function setDate()
    {
        return $this->date;
    }
}