<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */
namespace entity; // toujours le même nom que le dossier, pour que l'autoload puisse trouver le fichier
class Commande {

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $idCommande;

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $montant;

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $idMembre;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $date;

    
    //----------- GETTERS -----------------
    public function getIdCommande()
    {
        return $this->idCommande;
    }
    public function getMontant()
    {
        return $this->Montant;
    }
    public function getIdMembre()
    {
        return $this->idMembre;
    }
    public function getDate()
    {
        return $this->date;
    }
    
    //--------- SETTERS ------------------
    public function setDate()
    {
        $this->date = date('D M','Y','G:i');
        return $this->date;
    }
    
}
