<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */
namespace entity; // toujours le même nom que le dossier, pour que l'autoload puisse trouver le fichier
class DetailCommande {

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $idDetailCommande;

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $idCommande;

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $idProduit;

    //----------- GETTERS -----------------
    public function getIdDetailCommande()
    {
        return $this->idDetailCommande;
    }
    public function getIdCommande()
    {
        return $this->idCommande;
    }
    public function getIdProduit()
    {
        return $this->idProduit;
    }
}
