<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        User
 */
namespace entity; // toujours le même nom que le dossier, pour que l'autoload puisse trouver le fichier
require_once 'User.php';
use entity\User;

class Membre extends User {

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $nom;
    
	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $prenom;
    
    /**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $pseudo;
    
     /**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $mdp;
	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $email;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $sexe;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $ville;

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $cp;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $adresse;
    
    /**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $statut;


    //----------- GETTERS -----------------
    public function getNom()
    {
        return $this->nom;
    }
    
    public function getPseudo()
    {
        return $this->pseudo;
    }
    
    public function getMdp()
    {
        return $this->mdp;
    }
    
    public function getPrenom()
    {
        return $this->prenom;
    }
    
    public function getEmail()
    {
        return $this->email;
    }
    
    public function getSexe()
    {
        return $this->sexe;
    }
    
    public function getVille()
    {
        return $this->ville;
    }
    
    public function getCp()
    {
        return $this->cp;
    }
    
    public function getStatut()
    {
        return $this->statut;
    }
   
    //--------- SETTERS ------------------
    public function setNom($nom)
    {
        return $this->nom = $nom;
    }
    
    public function setPrenom($prenom)
    {
        return $this->prenom = $prenom;
    }
    
    public function setPseudo($pseudo)
    {
        return $this->pseudo = $pseudo;
    }
    
    public function setMdp($mdp)
    {
        return $this->mdp = $mdp;
    }
    
    public function setEmail($email)
    {
        return $this->email = $email;
    }
    
    public function setSexe($sexe)
    {
        return $this->sexe = $sexe;
    }
    
    public function setVille($ville)
    {
        return $this->ville = $ville;
    }
    
    public function setCp($cp)
    {
        return $this->cp = $cp;
    }
    
    public function setStatut($statut)
    {
        return $this->statut = (int)$statut;
    }
}
