<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        User
 */
namespace entity; // toujours le même nom que le dossier, pour que l'autoload puisse trouver le fichier
require_once 'User.php';
use entity\User;

class Membre extends User {

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $nom;
    
	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $prenom;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $email;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $sexe;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $ville;

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $cp;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $adresse;


    //----------- GETTERS -----------------
    public function getNom()
    {
        return $this->nom;
    }
    public function getPrenom()
    {
        return $this->prenom;
    }
    public function getEmail()
    {
        return $this->email;
    }
    public function getSexe()
    {
        return $this->sexe;
    }
    public function getVille()
    {
        return $this->ville;
    }
    public function getCp()
    {
        return $this->cp;
    }
   
    //--------- SETTERS ------------------
    public function setNom($nom)
    {
        if(is_string($nom)) {
            $this->nom = $nom;
        }
    }
    public function setPrenom(string $prenom)
    {
        if(is_string($prenom)) {
            $this->prenom = $prenom;
        }
    }
    public function setEmail($email)
    {
        return $this->email = $email;
    }
    public function setSexe($sexe)
    {
        if($sexe === 'm'|| $sexe === 'f') {
            return $this->sexe = $sexe;
        }  else {
            echo "Veuillez saisir 'm' ou 'f'";
        }
    }
    public function setVille($ville)
    {
        if(is_string($ville)) {
            $this->ville = $ville;
        }
    }
    public function setCp($cp)
    {
        if(is_int($cp)) {
            $this->cp = $cp;
        }
    }
}
