<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */
namespace entity; // toujours le même nom que le dossier, pour que l'autoload puisse trouver le fichier
class Newsletter {

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $idNewsletter;

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $idMembre;

    //----------- GETTERS -----------------
    public function getIdNewsletter()
    {
        return $this->idNewsletter;
    }
    public function getIdMembre()
    {
        return $this->idMembre;
    }
}
