<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */
namespace entity; // toujours le même nom que le dossier, pour que l'autoload puisse trouver le fichier
class Produit {

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $id_produit;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $date_arrivee;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $date_depart;

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $id_salle;

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $id_promo;

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $prix;

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $etat;


}
?>