<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Config {

	/**
	 * Stock dans un array toutes les infos de connexion à la BDD.
Issu de parameters.php
	 * @var array
	 * @access protected
	 */
	protected  $parameters;
    protected $server;
    const ROOT_SITE = "/lokisalle/web/";
    //const ROOT_SERVER = $server;



	/**
	 * @access public
	 */

	public final  function __construct() {
        print_r($_SERVER['DOCUMENT_ROOT']);
	}


	/**
	 * @access public
	 */

	public final  function getParametersConnect() {

	}


}
?>