<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class PdoManager {

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $instance;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $pdo;


}
?>