<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Config {

/**
* Stocke dans un array toutes les infos de connexion à la BDD.
* Issu de parameters.php
* 
*/
       
    protected $parameters;
    
    public function __construct()
    {
        require __DIR__ . '/parameters.php';
        $this->parameters = $parameters; // $parameters est issu du require config/parameters.php
    }
    public function getParametersConnect()
    {
        return $this->parameters['connect'];
    }
    
    public function getSiteParam()
    {
        return $this->parameters['siteParam'];       
    }
}

/*
$a = new Config();
$a->getSiteParam();
$a->getParametersConnect();
 * 
 */