<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */
namespace repository; // toujours le même nom que le dossier, pour que l'autoload puisse trouver le fichier

class EntityRepository {

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $db;


}
?>