<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        EntityRepository
 */
namespace repository; // toujours le même nom que le dossier, pour que l'autoload puisse trouver le fichier

require_once('EntityRepository.class.php');

class MemberRepository extends EntityRepository {


	/**
	 * @access public
	 * @return array
	 */

	public final  function getAllMember() {

	}


}
?>