<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        EntityRepository
 */
require_once('EntityRepository.class.php');

class AvisRepository extends EntityRepository {


	/**
	 * @access public
	 * @return array
	 */

	public final  function getAllAvis() {

	}


}
?>