<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class EntityRepository {

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $db;


}
?>