<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Avis {

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $id_avis;

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $id_membre;

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $id_salle;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $commentaire;

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $note;


}
?>