<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Commande {

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $id_commande;

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $montant;

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $id_membre;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $date;


}
?>