<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class DetailCommande {

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $id_detail_commande;

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $id_commande;

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $id_produit;


}
?>