<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Newsletter {

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $id_newsletter;

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $id_membre;


}
?>