<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Promotion {

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $id_promo;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $code_promo;

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $reduction;


}
?>