<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Salle {

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $id_salle;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $pays;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $ville;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $sexe;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $ville;

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $cp;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $adresse;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $description;

	/**
	 * 
	 * @var integer
	 * @access protected
	 */
	protected  $capacite;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $photo;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $categorie;


}
?>