<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

abstract class User {

	/**
	 * 
	 * @var int
	 * @access protected
	 */
	protected  $id_membre;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $pseudo;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $mdp;

	/**
	 * Droit : admin = 1; membre = 0
	 * @var integer
	 * @access protected
	 */
	protected  $statut;

	public function isConnected($user)
	{
		if($_SESSION['connected'] == true)
		{
			return true;
		}
	}
}
?>